### ISSUE TITLE
Add queue shutdown switch to dashboard

### ISSUE THREAD

**Issue by sihil** [guardian/riff-raff#119]
There is a need to make deployment easier. One approach is to deploy by copying the JAR into place and then flipping a switch that will shutdown as soon as there are no deploys running. This saves a human having to do the same thing.

This needs some extra work on the init script to restart the process rather than simply exiting (specific exitcode?)

Looks like NettyServer.stop() might be the right approach although System.exit(?) might be sufficient.

**Comment by philwills** [comment]
This has been done.
