### ISSUE TITLE
Elasticsearch deploys should check for a green cluster state first

### ISSUE THREAD

**Issue by maxharlow** [guardian/riff-raff#153]
Before doing anything, it would be useful if Elasticsearch deploys checked that the cluster is in a green state. Without that it's pretty much bound to fail: I'd be nice if that failure happened earlier before it's started up all these new machines.

Riffraff already checks that there is enough capacity to deploy: this would be similar.

**Comment by philwills** [comment]
Done, https://github.com/guardian/deploy/blob/master/magenta-lib/src/main/scala/magenta/deployment_type/ElasticSearch.scala#L25

**Comment by maxharlow** [comment]
horray!

**Comment by philwills** [comment]
Always working to keep you happy @maxharlow
