### ISSUE TITLE
Add button to retry a failed deploy

### ISSUE THREAD

**Issue by sihil** [guardian/riff-raff#168]
Sometimes you simply want to try to run the same deploy again with exactly the same parameters. There should be a button that allows you to do this on a failed deploy page.

**Comment by sihil** [comment]
As mentioned the other day @jennysivapalan - although it could always be there regardless of whether it failed or not?

**Comment by alexduf** [comment]
I definitely see the use of a button here no matter what. I have seen myself successfully deploying a project only to realise the configuration was wrong. So I have to fix the configuration and deploy the same thing again.
A button would help a lot in that case!

**Comment by jennysivapalan** [comment]
👍 definitely - I'm happy to try and give this a bash and learn some Riff Raff knowledge. I'll let you know how I get on next week @sihil @alexduf
