### ISSUE TITLE
Status updates force scrolldown

### ISSUE THREAD

**Issue by ScalaWilliamTG** [guardian/riff-raff#236]
I tried to click "Show verbose log lines" during a deployment, then it suddenly scrolled down and I clicked "Stop this deploy" by accident.

**Comment by sihil** [comment]
I've fixed some of the logic around the scrolldown in #387 which might help with this. It should only force scrolldown if the bottom of the log is on the screen.

Not sure how best to resolve this long term.

**Comment by philwills** [comment]
Closing this for now, as I think it's been ameliorated.
