### ISSUE TITLE
Upgrade to play 2.5

### ISSUE THREAD

**Issue by sihil** [guardian/riff-raff#301]
We should modernise Riff-Raff to play 2.5.

During this process we should change the CSRF implementation introduced in #300 to use the global filter with some holes punched in it for the API.

**Comment by cb372** [comment]
![image](https://cloud.githubusercontent.com/assets/106760/15706038/95d6a680-27e9-11e6-81e6-e42d5686cdab.png)

Upgrading Play apps to 2.5.x is a hobby of mine!
