### ISSUE TITLE
Apply a code formatter

### ISSUE THREAD

**Issue by cb372** [guardian/riff-raff#335]
The code is a royal mess.

sbt-scalariform is a classic, but I hear [scalafmt](https://olafurpg.github.io/scalafmt/) is where the cool kids are at these days.

**Comment by philwills** [comment]
I have a particular personal animus towards code formatters. They always stop me doing things I explicitly want to do and historically I've had issues with them resulting in SBT/IntelliJ churn.

Things may be much improved now, but I've never been able to last more than a week with one before getting frustrated and ripping it out.

**Comment by cb372** [comment]
Even if you're a philistine who hates nice things, could we at least run a formatter over the code *once*? After that you're free to mess it all up again.

**Comment by philwills** [comment]
Yea, that sounds a reasonable compromise.

**Comment by philwills** [comment]
See also #434

**Comment by AWare** [comment]
I don't think this is likely to happen anytime soon, and we've lost enough people that the history is more valuable than when we last decided the history was too valuable to lose.
