### ISSUE TITLE
'Uploaded 0 assets' warning should be more prominent

### ISSUE THREAD

**Issue by philmcmahon** [guardian/riff-raff#482]
The 'frontend-static' step of this build: https://riffraff.gutools.co.uk/deployment/view/3d0241fe-411a-48e9-97ee-3424a85a3585 has a warning on it, but where the warning comes from is hard to tell until you open up the different build steps. For theguardian.com not having any assets is quite sad, so it would be good to make it immediately obvious what the problem is.

**Comment by katebee** [comment]
Fixed by #489 🎉
