### ISSUE TITLE
Wrong commit git URL

### ISSUE THREAD

**Issue by mxdvl** [guardian/riff-raff#598]
On `dotcom:all` the commit url contains a `.git` that should not be there. This will shortly be turned into a PR.

``` git
⛔ https://github.com/guardian/frontend.git/commit/2b92e57bf603c99d080c7c114f1c74f968dae185  
✅ https://github.com/guardian/frontend/commit/2b92e57bf603c99d080c7c114f1c74f968dae185
```

e.g. https://riffraff.gutools.co.uk/deployment/view/192574fb-ddee-4377-b7da-5257206a6bcd

**Comment by akash1810** [comment]
Fixed in https://github.com/guardian/riff-raff/pull/645.
